// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PicoBeer.Dal;

namespace PicoBeer.Migrations
{
    [DbContext(typeof(PicoBeerContext))]
    partial class PicoBeerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PicoBeer.Domain.Hop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Alpha");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Hop");
                });

            modelBuilder.Entity("PicoBeer.Domain.Malt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<double>("Ebc");

                    b.Property<int>("ExtractFactor");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Malt");
                });

            modelBuilder.Entity("PicoBeer.Domain.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("test1")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("PicoBeer.Domain.Yeast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Attenuation");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Yeast");
                });
#pragma warning restore 612, 618
        }
    }
}
